#!/bin/sh
okpat=*.sjson
kopat=*.morbigerror

# cleanup
find . -name "$okpat" -o -name "$kopat" -delete

# run
find . -name "*.sh" | xargs morbig --continue-after-error --as simple

# summarize
echo "==============================="
echo -n "Should fail:    "
echo -n "OK: "
echo -n $(find bad -name "$kopat" | wc -l)
nrbadsuccess=$(find bad -name  "$okpat" | wc -l)
echo " KO: $nrbadsuccess"

echo -n "Should succeed: "
echo -n "OK: "
echo -n $(find good -name  "$okpat" | wc -l)
nrgoodfailures=$(find good -name  "$kopat" | wc -l)
echo " KO: $nrgoodfailures "
echo "==============================="
if [ $nrgoodfailures -gt 0 ]; then
    echo "Failing tests:"
    find good -name  "$kopat"
fi


